### ISSUE TITLE
copyright question, use of your icon

### ISSUE THREAD

**Issue by simon300000** [Jannchie/biliob-frontend#40]
Hello,
I made a website tracks some bilibili user, <https://vtbs.moe>
I add a button that directs to the users page on your website <https://www.biliob.com>.

For example,
<https://vtbs.moe/detail/1473830>
<img width="360" alt="image" src="https://user-images.githubusercontent.com/12656264/57981128-235c1180-7a66-11e9-80e0-f4552c2f2a8e.png">
which uses your icon.

If its not good, I could remove it, so...

**Comment by Jannchie** [comment]
It’s great.
